package com.tbs.covidtracker

import com.tbs.covidtracker.di.DaggerAppComponent
import dagger.android.AndroidInjector
import dagger.android.DaggerApplication

class MainApplication:DaggerApplication() {
    /**
     * Tell Dagger which [AndroidInjector] to use - in our case
     * [com.tbs.covidtracker.di.AppComponent]. `DaggerAppComponent`
     * is a class generated by Dagger based on the `AppComponent` class.
     */
    override fun applicationInjector(): AndroidInjector<out DaggerApplication> {
        return DaggerAppComponent.factory().create(this)
    }
}